services:
  tilda-exporter:
    build: .
    env_file:
      - .env
    environment:
      - GIT_CONFIG_NAME=${GIT_CONFIG_NAME:-Tilda Exporter}
      - GIT_CONFIG_EMAIL=${GIT_CONFIG_EMAIL:-tilda-exporter@example.com}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - tilda-network
    ports:
      - "${TILDA_PORT}:${TILDA_PORT}"
    volumes:
      # Монтирование директорий для статических файлов
      - ./static:/${TILDA_STATIC_PATH_PREFIX}
      - ./static:/${TILDA_HTML_PATH}
      - ./static/images:/${TILDA_IMAGES_PATH}
      - ./static/css:/${TILDA_CSS_PATH}
      - ./static/js:/${TILDA_JS_PATH}
      # Если включен Git, монтируем .git директорию
      - .git:/app/.git:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://static.tildacdn.com"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  tilda-network:
    driver: bridge
