services:
  tilda-exporter:
    build: .
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - tilda-network
    ports:
      - "${TILDA_PORT}:${TILDA_PORT}"
    volumes:
      # Монтируем директории для статических файлов с правильными путями
      - ./${TILDA_HTML_PATH}:/app/${TILDA_HTML_PATH}
      - ./${TILDA_IMAGES_PATH}:/app/${TILDA_IMAGES_PATH}
      - ./${TILDA_CSS_PATH}:/app/${TILDA_CSS_PATH}
      - ./${TILDA_JS_PATH}:/app/${TILDA_JS_PATH}
      # Если включен Git, монтируем .git директорию
      - .git:/app/.git:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://static.tildacdn.com"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  tilda-network:
    driver: bridge
