version: '3.8'

services:
  tilda-exporter:
    build: .
    env_file:
      - .env
    ports:
      - "${TILDA_PORT}:${TILDA_PORT}"
    volumes:
      # Монтирование директорий для статических файлов
      - ${TILDA_STATIC_PATH_PREFIX}:/${TILDA_STATIC_PATH_PREFIX}
      - ${TILDA_HTML_PATH}:/${TILDA_HTML_PATH}
      - ${TILDA_IMAGES_PATH}:/${TILDA_IMAGES_PATH}
      - ${TILDA_CSS_PATH}:/${TILDA_CSS_PATH}
      - ${TILDA_JS_PATH}:/${TILDA_JS_PATH}
      # Если включен Git, монтируем .git директорию
      - .git:/app/.git:rw
    restart: unless-stopped 