version: '3'

services:
  tilda-exporter:
    build: .
    image: "fallenchromium/tilda-static-pages-exporter"
    environment:
      TILDA_PUBLIC_KEY: ${TILDA_PUBLIC_KEY}
      TILDA_SECRET_KEY: ${TILDA_SECRET_KEY}
      TILDA_PROJECT_ID: ${TILDA_PROJECT_ID}
      TILDA_STATIC_PATH_PREFIX: /static/
      GIT_USERNAME: ${GIT_USERNAME:-}
      GIT_PASSWORD: ${GIT_PASSWORD:-}
      GIT_REMOTE_URL: ${GIT_REMOTE_URL:-}
      TILDA_HOST: ${TILDA_HOST:-0.0.0.0}
      TILDA_PORT: ${TILDA_PORT:-5000}
    ports:
      - "${TILDA_PORT:-5000}:5000"
    volumes:
      - ./static/:/static/