version: '3.8'

services:
  tilda-exporter:
    build: .
    ports:
      - "${TILDA_PORT:-8000}:8000"
    volumes:
      - ./static:/app/static
    environment:
      - TILDA_PUBLIC_KEY=${TILDA_PUBLIC_KEY}
      - TILDA_SECRET_KEY=${TILDA_SECRET_KEY}
      - TILDA_PROJECT_ID=${TILDA_PROJECT_ID}
      - TILDA_HOST=0.0.0.0
      - TILDA_PORT=8000
      - TILDA_STATIC_PATH_PREFIX=static/
      - TILDA_HTML_PATH=static/
      - TILDA_IMAGES_PATH=static/images/
      - TILDA_CSS_PATH=static/css/
      - TILDA_JS_PATH=static/js/
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_TOKEN}
      - GIT_REMOTE_URL=${GIT_REMOTE_URL}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - tilda-network
    restart: unless-stopped

networks:
  tilda-network:
    driver: bridge